metadata: Try to fix  FC121: Cookbook depends on cookbook made obsolete by Chef 14.
NOTE:  Using chef_version here was resulting in Array of Gem::Dependency, which caused error:

    ERROR: Chef::Exceptions::InvalidCookbookVersion: '[<Gem::Dependency type=:runtime name="chef" requirements=">= 12.0">]' does not match 'x.y.z' or 'x.y'
rake aborted!

Changing this to use Chef::VERSION.to_s ensures that version comparison happens on string

Reference:  https://github.com/berkshelf/berkshelf/issues/1814